version: '3.7'

services:
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  server:
    build: ./server
    restart: always
    ports:
      - 80:80
    depends_on:
      - mysql
    environment:
      DB_PASS: pass
      DB_USER: root
      DB_HOST: mysql
      DB_NAME: db
      DB_MAX_RETRIES: 5
      PORT: 80
      JWT_SECRET_KEY: topsecretkeydonotshare